// ======================================= 月海KP
export const CocYuehai = [
  {
    "name": "疯狂的艺术",
    "description": "1922年10月的一个星期三，一位伊丽莎白布什小姐联系到了你们，布什小姐请求你们帮助寻找他的兄弟迈克尔，他同时也为之前雇佣的私家侦探啊失踪而感到困惑。",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 2,
    "tags": [],
    "era": "1920美国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "铅毒之果",
    "description": "车的燃料表出了问题，这使得调查员被困在一条偏僻的路上，最近的镇子也要几英里远，但附近就有一栋大房子，住在房子里的人或许有汽油或者甚至有电话可以向外求助。",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 3,
    "tags": [],
    "era": "1920美国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 1,
  },
  {
    "name": "猩红文档",
    "description": "这个模组的事件由一场毫无预兆的死亡引发，死亡者是密斯卡托尼克大学的一名教师卡勒斯莱特教授，他死于一个奇怪的环境下并且有着侵吞和盗窃密大藏物的可能，而这可能给密大带来难以承受的丑闻。作为这所大学的一名管理者布莱斯法伦，将聘用调查员们对卡勒斯莱特的突然死亡进行调查，并且更为重要的是，对于失踪了的原本在莱特 看管下的某贵重文件进行寻找，最好是能在这文件的法定拥有者了解到这属于他的东西已经丢失了之前。",
    "players": "3-6人",
    "duration": "6-8h",
    "difficulty": 3,
    "tags": ["百分百撕卡率"],
    "era": "1920美国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 1,
  },
  {
    "name": "诅咒之音",
    "description": "你们抱着不同的目的来到了一家灵异事件频发的宾馆。",
    "players": "3-6人",
    "duration": "4h",
    "difficulty": 2,
    "tags": ["日式"],
    "era": "现代日本",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "复足",
    "description": "调查员受邀来到伊利诺伊州芝加哥市参加，为备受喜爱的怪奇作家哈里森·保罗·莱肯塔夫举办的为期三天的庆典，如往常一样庆典在临近芝加哥奥黑尔国际机场的曲径商业旅店举行，整个周末的内容包括：莱肯塔夫的作品讨论会、各种取材自莱肯塔夫作品的游戏以及作为压轴的粉丝自制短片首映式。",
    "players": "3-6人",
    "duration": "6h",
    "difficulty": 2,
    "tags": ["蜘蛛"],
    "era": "1920美国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "无尽食欲",
    "description": "你们原本都在自己的人生轨迹上因为自己的目前而努力前进着，却因为一个共同的朋友“石泽先生”被聚集在了一起。你们并不知道发生了什么，但是都记得当时的通话内容“近来可好我的老朋友，说起来有些唐突，我知道你是一个很出色并且有能力的人，我需要你的帮助。”有些寒冷的秋风讲你们从回忆之中拉了回来，你们看着这个记忆中枯瘦的年轻人，他如今已是一副大腹便便的模样，站在饭店的门口笑盈盈的迎接着你们。究竟是什么样的事情需要这么多人才能解决，你不禁感到一阵好奇。",
    "players": "3-6人",
    "duration": "8h+",
    "difficulty": 2,
    "tags": ["日式", "重口"],
    "era": "现代日本",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 0,
  },
  // 分解器
]
export const CocYuehaiKey = CocYuehai.map(el => el.name)

// ======================================= 暂时店内的一些本(能力强的能带)
export const CocStore = [
  {
    name: "《幽暗之门》",
    originName: "Doors To Darkness",
    description: "官方守秘人手册中包含的经典模组合集，涵盖了多个入门级和进阶级冒险。",
    players: "3-6人",
    duration: "多样",
    difficulty: 1,
    tags: ["官方", "合集", "经典", "入门"],
    era: "1920美国",
    requirements: "标准车卡",
    isNewbie: true,
    type: "coc",
    kp: "",
    author: "Chaosium Inc. 官方",
    skills: "",
    notes: "",
    mastery: "",
    // cocType: "标准COC",
    isCollection: true,
    weight: 0,
    modules: [
      {
        "name": "了却幻梦",
        "originName": "None more Black",
        "description": "密斯卡托尼克大学学生死亡事件，事件背后另有邪恶交易？！",
        "players": "2-6人",
        "duration": "4-8h",
        "difficulty": 2,
        "tags": [],
        "era": "1920美国,密大",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海",
        "author": "Brian M. Sammons",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 1,
      },
      {
        "name": "岭下暗影",
        "originName": "The Darkness Beneath the Hill",
        "description": "调查员们被他们的一位熟人，乔什·文斯考特召集在一起，后者近日在其地窖中找到了一条隧道。",
        "players": "2-6人",
        "duration": "???",
        "difficulty": 1,
        "tags": [],
        "era": "1920英国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海",
        "author": "Christopher Smith Adair",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "哈索恩山",
        "originName": "Genius Loci",
        "description": "绝望的呼救与平静的拒绝，竟出自同一人之口。\n当挚友同时向你传递极致的恐惧与诡异的安宁，你意识到——有些真相，必须亲自揭开。",
        "players": "2-6人",
        "duration": "???",
        "difficulty": 1,
        "tags": [],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海",
        "author": "Brian Courtemanche",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "湖之仆从",
        "originName": "Servants of the Lake",
        "description": "这是来自于知名银行家杰拉德·弗雷泽的委托，你们认识且你们也知道钱对他而言不过是数字。委托很简单，他的独子詹姆斯失踪了，在这一切还没有发酵成丑闻的时候，把这个混小子带回来！",
        "players": "3-6人",
        "duration": "4-6h",
        "difficulty": 1,
        "tags": ["新手团"],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": true,
        "type": "coc",
        "kp": "六",
        "author": "Glynn Owen Barrass",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "血浓于水",
        "originName": "Ties that Bind",
        "description": "这是来自于著名铁路大亨之女伊娜德·卡琳顿的求助，据说他们的家的喷泉被无故损坏了，现在需要人来搞清楚到底是人为的破坏还是自然的侵蚀。你们的身份有可能是私家侦探，也有可能是急于讨好她的警局人员，也有可能是听闻这一消息的闲杂人员。",
        "players": "3-6人",
        "duration": "6-8h",
        "difficulty": 2,
        "tags": ["标准团"],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "六",
        "author": "Tom Lynch",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 2,
      },
    ],
  },
  {
    name: "《旧日支配者们》",
    originName: "The Great Old Ones",
    description: "官方经典模组合集，涵盖了多个难度较高的冒险冒险。",
    players: "3-6人",
    duration: "多样",
    difficulty: 3,
    tags: ["官方", "克苏鲁", "经典", "标准"],
    era: "1920美国",
    requirements: "标准车卡",
    isNewbie: false,
    type: "coc",
    kp: "",
    author: "Chaosium",
    skills: "",
    notes: "",
    mastery: "",
    // cocType: "标准COC",
    isCollection: true,
    weight: 0,
    modules: [
      {
        "name": "孽生",
        "originName": "The Spawn",
        "description": "其调查员们到了蛮荒般的西部调查一宗谋杀案，观察阶级冲突，并发现比预期更多的恶意。",
        "players": "3-6人",
        "duration": "8h+",
        "difficulty": 3,
        "tags": [],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海",
        "author": "Harry Cleaver",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "禁止之水",
        "originName": "Still Water",
        "description": "调查员们接了简单的任务往东边去了，在血粼粼的惨剧之中，发现所有藏书狂都是同类...",
        "players": "3-6人",
        "duration": "6-8h",
        "difficulty": 2,
        "tags": [],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海",
        "author": "L.N.Isynwill, Doug Lyons",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "告诉我, 汝是否见过黄色邪印",
        "originName": "Tell Me, Have You Seen The Yellow Sign",
        "description": "我们的英雄来到新奥尔良，追寻英勇的往昔，却被卷入恐怖的当下。",
        "players": "3-6人",
        "duration": "???",
        "difficulty": 3,
        "tags": [],
        "era": "192_美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海",
        "author": "Kevin A. Ross",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "暗中来客",
        "originName": "One In Darkness",
        "description": "一个年轻的记者需要得到帮助，虽然一般而言震撼波士顿的犯罪浪潮与他毫无关系。",
        "players": "3-6人",
        "duration": "8h+",
        "difficulty": 2,
        "tags": [],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海",
        "author": "Doug Lyons with L.N.Isynwill",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "苍白的神",
        "originName": "The Pale God",
        "description": "调查员在对一所臭名昭著的农舍进行调查时，面临着一场惊心动魄的死亡。",
        "players": "3-6人",
        "duration": "???",
        "difficulty": 3,
        "tags": [],
        "era": "1920英国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海",
        "author": "Kevin A. Ross",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "恶月当空",
        "originName": "Bad Moon Rising",
        "description": "调查员参加了一个科学会议，懂得如何尊重恐惧，通过一次奇怪的旅程通往更加奇异的终点。",
        "players": "3-6人",
        "duration": "???",
        "difficulty": 3,
        "tags": [],
        "era": "192_英国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海",
        "author": "Marcus L. Rowland",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
    ],
  },
]
export const CocStoreKey = CocStore.map(el => el.name)

// ======================================= 六KP
export const CocLiu = [
  {
    "name": "23号休息站",
    "originName": "",
    "description": "你从没见过像这样的暴风雪，十月的爱达荷山脉的天气可能不太好，但现在出现在你们面前的却是一片白色的苍茫大地……",
    "players": "3-6人",
    "duration": "4-5h",
    "difficulty": 1,
    "tags": ["新手团"],
    "era": "现代美国",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "coc",
    "kp": "六",
    "author": "",
    "skills": "",
    "notes": "纯新人模组",
    "mastery": "掌握",
    "weight": -1,
  },
  {
    "name": "黑水溪",
    "description": "黑水溪是一个位于马萨诸塞州的小镇。1926年9月下旬，正值禁酒令时期，你们因为各自的原因而来到了这里。 ",
    "players": "3-6人",
    "duration": "6-12h",
    "difficulty": 2,
    "tags": ["美模", "经典"],
    "era": "1926美国",
    "requirements": "车卡，预设卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "六",
    "author": "埃兰迪斯",
    "skills": "御三家、战斗",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "星尘的研究",
    "originName": "A STUDY IN STARDUST",
    "description": "在2012年的12月17日圣诞节前夕，你们收到了一封来自于伦敦贝克街 221B 博物馆管理员的求助信。管理员朱蒂·康伯巴奇希望得到你们的帮助，希望你们能够帮助她找回丢失展品并阻止她口中“末日” 。",
    "players": "3-6人",
    "duration": "10h起",
    "difficulty": 3,
    "tags": ["标准团"],
    "era": "2012年美国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "六",
    "author": "The leaf",
    "skills": "",
    "notes": "",
    "mastery": "",
    "weight": 2,
  },
  {
    "name": "小瓢虫快回家",
    "originName": "LADYBUG, LADYBUG, FLY AWAY HOME ",
    "description": "一桩看似寻常的绑架案将你们的命运串联在一起。可当你们剥开层层迷雾，才惊觉自己触碰到的，是一个远比想象中更加黑暗与骇人的真相。",
    "players": "3-6人",
    "duration": "8h起",
    "difficulty": 2,
    "tags": ["标准团"],
    "era": "现代美国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "六",
    "author": "Jeff Moeller ",
    "skills": "",
    "notes": "",
    "mastery": "",
    "weight": 2,
  },
  {
    "name": "约克郡恐怖事件",
    "originName": "The Yorkshire Horrors",
    "description": "1896年4月25日，你们会在早上收到一封来自贝克街的信。信封并非什么几便士一捆的便宜货，而是精美的印制品。信封用火漆牢牢封好，调查员可以看到上边有S.H.的火漆印。",
    "players": "3-6人",
    "duration": "4-5h",
    "difficulty": 5,
    "tags": ["福尔摩斯","推理","维多利亚晚期"],
    "era": "近代欧洲",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "6",
    "author": "James Kevin Ramos",
    "skills": "",
    "notes": "原来夏洛克·福尔摩斯也需要我们的帮忙呀",
    "mastery": "掌握模组",
    "weight": 1,
  },
  {
    "name": "德州大爆炸",
    "originName": "",
    "description": "1952年4月16日，与各位关系匪浅的亚历山大·汤普森向你们发出了邀请，作为为人仗义，挥金如土的伙伴，你们之前一起干过不少事，而在这一天，他说搞到了'绝对劲爆的玩意儿'，今天是专门邀请各位前来分享",
    "players": "3-6人",
    "duration": "4-5h",
    "difficulty": 1,
    "tags": ["新手团","线性","拯救世界"],
    "era": "近代美国",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "coc",
    "kp": "6",
    "author": "",
    "skills": "",
    "notes": "战后明媚奔放的50年代，热情洋溢的聚会，难得的假期，一切都是那么美好",
    "mastery": "掌握模组",
    "weight": -1,
  },
  {
    "name": "地狱之门",
    "originName": "",
    "description": "1925年的上海滩，《申报》的小记者郑新学突然自杀，事发于法租界石库门公寓，在巡捕房一些列侦查之后，计划结案。但！郑新学的父亲，礼和洋行的大买办郑日昨儿却不认为如此，小儿子最近没受什么困难挫折，不应该随意自杀。是故，你们将会受到郑家长子郑新科的委托，调查郑新学自杀一案……",
    "players": "3-6人",
    "duration": "8-10h",
    "difficulty": 4,
    "tags": ["上海滩","沙盒","错综复杂"],
    "era": "近代中国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "6",
    "author": "",
    "skills": "",
    "notes": "在黄赌白所带来的滚滚金钱之下，上海仿佛献血浇灌的玫瑰，显现出畸形的繁荣:洋老爷、华人实业资本家和流氓大亨们谈笑风生，翻手为云覆手为雨，联手统治着这座不夜之城。",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "七月十四青松镇",
    "originName": "",
    "description": "曦光从天际挥洒而下，四周的树林寂寥无声。客车斜斜躺在溪水里，引擎盖上冒着青烟。然而令你们惊异的是，所有人的身上似乎都没有很严重的外伤，只是头脑有些不清楚，应是车祸的后遗症。稀疏的树林中弥漫着薄薄的雾气，淡淡的机油味道萦绕在鼻头。虽然雾气弥漫，但借着山高，远处的青松镇在氤氲中若隐若现",
    "players": "3-6人",
    "duration": "12h",
    "difficulty": 5,
    "tags": ["寂静岭风格","中式恐怖","妖魔鬼怪","故事性"],
    "era": "现代中国",
    "requirements": "预设卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "6",
    "author": "",
    "skills": "",
    "notes": "人之魂善而魄恶，人之魂灵而魄愚。其始来也，一灵不泯，魄附魂以行；其既去也，心事既毕，魂一散而魄滞。魂在，则其人也；魂去，则非其人也。",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "谢娘娘点化",
    "originName": "",
    "description": "2000年中国湖北省武汉，8月8日晚7点15分，你们驾驶一辆劫来的黑色富康逃往城外，一辆警车紧随其后，在这个狂风暴雨的夜晚，山路愈加难行。",
    "players": "3-6人",
    "duration": "12h",
    "difficulty": 5,
    "tags": ["沙盒","中式恐怖","民俗","惊悚"],
    "era": "现代中国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "6",
    "author": "",
    "skills": "",
    "notes": "破山中贼易，破心中贼难，展现人性，考验人性",
    "mastery": "掌握模组",
    "weight": 0
  },
  {
    "name": "远古的礼物",
    "originName": "",
    "description": "1933年6月的一个夜晚，BOI的委托如期而至，前往华尔街73号集合，有任务需要你们完成。伴随着刺耳的警笛声在夏日的夜空中回响，你们到达了这件办公室……",
    "players": "3-6人",
    "duration": "4-5h",
    "difficulty": 1,
    "tags": ["新手团","线性","调查","官方委托"],
    "era": "近代美国",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "coc",
    "kp": "6",
    "author": "",
    "skills": "",
    "notes": "种族歧视永远是一道跨不去的坎",
    "mastery": "掌握模组",
    "weight": -1,
  },
]
export const CocLiuKey = CocLiu.map(el => el.name)

// ======================================= 合并并排序的模组列表
export const CocAllModules = [...CocYuehai, ...CocStore, ...CocLiu]
  .sort((a, b) => {
    // 先排新手
    // 第一优先级：isNewbie (true 在前) 
    if (a.isNewbie !== b.isNewbie) {
      return a.isNewbie ? -1 : 1
    }
    
    // 第二优先级：权重 (有值且数值大的在前)
    if (a.weight !== b.weight) {
      // 如果都有权重，按权重降序
      if (a.weight !== null && b.weight !== null) {
        return b.weight - a.weight
      }
      // 只有一个有权重，有权重的在前
      if (a.weight !== null) return -1
      if (b.weight !== null) return 1
    }
    
    // 第三优先级：难度 (数值小的在前)
    return a.difficulty - b.difficulty
  })
// 排序的改一下 ✅
  
// 上一些双人模组 纯新手开 车卡和跑团分开收费
// 追书人

// 有合集的模组 用合集名归类 ✅