// ======================================= 燕窝KP
export const CocYanwo = [
  // {
  //   "name": "别淋湿",
  //   "description": "这是一个晴朗的午后，几位高中生因为各自的原因在教室中自习。由于下午的课还要两个小时才会开始，所以房间中除了他们并没有其它的学生或者老师。而随着房间中的气温渐渐下降，而且开始有一股潮湿的气息，他们开始意识到，不知道在什么时候，一场突如其来的大雨笼罩了他们……",
  //   "players": "2-4人",
  //   "duration": "2-5h",
  //   "difficulty": 1,
  //   "tags": ["新手本"],
  //   "era": "现代中国,高中",
  //   "requirements": "车卡",
  //   "isNewbie": true,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "湖中羊",
  //   "skills": "侦查、聆听、攀爬",
  //   "notes": "难度可调，老手新手都可以用来团建\nroll 5选1，符合高中生人设，技能上限80/60。\n【推荐意志强一点，但是弱了或许有不一样的节目效果？】",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "失衡·前几天",
  //   "description": "地铁上，你和两个孩子被卷进一场奇怪的事件。你必须选择牺牲一人以脱险……或者还有更好的选择？",
  //   "players": "1-2人",
  //   "duration": "3-4h",
  //   "difficulty": 1,
  //   "tags": ["新手本"],
  //   "era": "现代中国,地铁",
  //   "requirements": "车卡",
  //   "isNewbie": true,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "自燃",
  //   "skills": "侦查、精神分析、交涉技能。",
  //   "notes": "非常有趣且适合新人的模组，解法多样，封闭空间。\n可携带物品必须是可以过地铁安检的东西",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "活神之手",
  //   "description": "接着我沉入了深渊，并听见了身着黄衣的王向着我的灵魂耳语：“落入活神之手中是件可怕的事！”   ———Robert W· Chambers ",
  //   "players": "1人",
  //   "duration": "3-5h",
  //   "difficulty": 1,
  //   "tags": ["单人", "新手本"],
  //   "era": "1920美国",
  //   "requirements": "车卡",
  //   "isNewbie": true,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "Daniel Harms",
  //   "skills": "御三家，战斗技能、体现你是一位学者的技能",
  //   "notes": "经典美模，正统coc风味\n调查员的身份必须为一位学者。",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "绯闻女孩",
  //   "description": "最近，关于女学生与教授的绯闻在布里托特大学不胫而走。数名学生声称自己确凿无疑地见到背影肖似苏珊娜的年轻女性衣衫不整地从不同教授的办公室内跑出。流言愈演愈烈，作为流言主角的苏珊娜在风口浪尖之时递交了休学申请。 \n调查员作为学校的行政人员，被要求调查系列流言的真相，并根据调查结果决定如何处置苏珊娜的休学申请。 \n切记：为了维护布里托特大学的声誉，无论调查结果如何，调查员不可报警，也不可通知相关政府部门。 调查员可以邀请数名同事一同调查，将此模组变为多人模组。",
  //   "players": "1-4人",
  //   "duration": "4-6h",
  //   "difficulty": 1,
  //   "tags": ["新手本"],
  //   "era": "现代美国",
  //   "requirements": "车卡",
  //   "isNewbie": true,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "catnico",
  //   "skills": "御三家、战斗技能（但不推荐战斗）",
  //   "notes": "国模优秀之作，难度不高，适合新手\n调查员身份必须是学校的行政人员。",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "常暗之厢",
  //   "description": "短篇秘密团。2013年午夜，三名背负隐秘的逃亡者登上末班电车，却坠入时空交错的牢笼。——你撕碎的是敌人的阴谋，还是另一个自己的生命剧本？",
  //   "players": "3人",
  //   "duration": "2-3h",
  //   "difficulty": 1,
  //   "tags": ["HO", "新手本"],
  //   "era": "现代日本,电车",
  //   "requirements": "车卡",
  //   "isNewbie": true,
  //   "type": "coc",
  //   "kp": "燕窝,月海,小隐",
  //   "author": "3266891494",
  //   "skills": "战斗技能、御三家",
  //   "notes": "经典模组常暗之厢，新手友好，已从coc6版改为最新的7版",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "就是你了",
  //   "description": "背景为现代日本，以调查员所在的学校为中心展开故事情节。调查员通过调查在学校中接二连三发生的奇怪事件，而让即将发生的悲剧防范于未然。",
  //   "players": "3-4人",
  //   "duration": "2-4h",
  //   "difficulty": 1,
  //   "tags": ["新手本", "高中生"],
  //   "era": "现代日本",
  //   "requirements": "车卡",
  //   "isNewbie": true,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "内山靖二郎",
  //   "skills": "御三家、战斗技能、交涉技能",
  //   "notes": "难度低，适合新手，开放空间\n必须为高中生，EDU必须在45-60区间内。天命5选1，或购点520。",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "内锈",
  //   "description": "你是法国海洋探险公司的一名底层员工，在公司的职务可以是清洁工、后勤人员、仓库管理员、维修工等。在经济危机的动荡局面中，你不得不努力保住自己的饭碗并寻求一切挣钱的机会。因此你接受公司邀请参加一项有报酬的测试工作：帮忙测试公司与科学家合作研发的一款计算机感官头盔“眼耳号”。",
  //   "players": "1人",
  //   "duration": "2-4h",
  //   "difficulty": 2,
  //   "tags": ["单人"],
  //   "era": "1980法国",
  //   "requirements": "roll 5选1，80/60",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "枫叶狐",
  //   "skills": "需要会说一口流利的法语，身手至少不赖。（但用到的技能检定很少，所以不做具体推荐）",
  //   "notes": "创意极佳，非常适合面团，推荐在跑团时做好记录\n（喜欢快速开始甚至可以不车直接玩）",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "必需品",
  //   "description": "春节临近，尽管除夕不放假，但是人们依然洋溢在每年一次的节日中，积极的准备着过年必需品——在这种氛围下，买买买和计划春节旅行变成了主流。 此时C世一座于市郊盛大开业的购物广场顺势进入了你们的视线——各色店铺一应俱全，多个能拍出漂亮照片的网红打卡点、近期新晋热门的十大必去餐厅、多个娱乐项目，再加上新开业的巨大优惠，怎么能不去！！！  ",
  //   "players": "3-4人",
  //   "duration": "4-5h",
  //   "difficulty": 2,
  //   "tags": [],
  //   "era": "现代中国",
  //   "requirements": "天命5选1，或者520购点。",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "Adam",
  //   "skills": "随便点，买买买快乐XD",
  //   "notes": "适合老手团建的茶番\n提前说好pc之间的关系，要有逛商场的目的！",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "失忆恋人",
  //   "description": "你（HO1）与你的恋人为了观赏鲸鱼而登上海洋献礼号，即将开启为期一周的甜蜜游轮之旅。 不料，你刚登船没多久便卷入一场谋杀案，遭到袭击后昏迷并失忆。醒来后竟然有三个自称是你恋人的人对你嘘寒问暖处处关怀，那么问题来了，谁才是你真正的恋人，谁又是凶手？",
  //   "players": "4人秘密团，有HO（有无PVP要看RP）",
  //   "duration": "6-8h",
  //   "difficulty": 2,
  //   "tags": ["HO"],
  //   "era": "故事发生地位于某国际游轮上",
  //   "requirements": "roll 5选1，其他按照HO来。",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "Fan",
  //   "skills": "侦查、聆听、攀爬、游泳、战斗技能、神秘学、英语 ",
  //   "notes": "扮演和调查难度较大（尤其是HO1），本团适合老手和熟人。【真的是正经团！！！】",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "登山裸男",
  //   "description": "近日，攀登某座无名山峰的登山队无故失踪。 接踵而来的，是幸存者着魔般在山下裸奔狂舞的诡异传闻。 你们受到相熟者的委托，前来调查登山队的失踪案件与这座山上隐藏着的秘密。 然而在山上等待你们的是——",
  //   "players": "3-4人",
  //   "duration": "4-8h",
  //   "difficulty": 2,
  //   "tags": [],
  //   "era": "现代美国",
  //   "requirements": "天命5选1，或购点520，上限85",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "五千",
  //   "skills": "coc的茶番，不做具体技能推荐，不过 你们是去爬山的所以建议至少要有导航",
  //   "notes": "【是半个正经团】，本质茶番，团建聊天娱乐。",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  {
    "name": "黑水溪",
    "description": "黑水溪是一个位于马萨诸塞州的小镇。1926年9月下旬，正值禁酒令时期，你们因为各自的原因而来到了这里。 ",
    "players": "3-6人",
    "duration": "6-12h",
    "difficulty": 2,
    "tags": ["美模", "经典"],
    "era": "1926美国",
    "requirements": "车卡，预设卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "燕窝,小隐",
    "author": "埃兰迪斯",
    "skills": "御三家、战斗",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 0,
  },
  // {
  //   "name": "过年（Over Kill the festival）",
  //   "description": "你们因为各种各样的原因，在新年之际搭上了这架从中国开往美国的飞机……",
  //   "players": "2-4人（4人最佳）",
  //   "duration": "4h（实际经验5-6h）",
  //   "difficulty": 2,
  //   "tags": ["HO"],
  //   "era": "中国开往美国的飞机上",
  //   "requirements": "车卡",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "p82fSt2q3Q",
  //   "skills": "战斗技能很重要，其次是御三家（侦察/聆听/图书馆）",
  //   "notes": "趣味性很强的模组，难度可调。尽管模组位于封闭场景内，仍然有相当大的自由度。\n有4个HO，pc国籍不限，但外国人至少要有50点以上的中文。\n以飞机作为舞台，KP和调查员需要十分注意携带物的管理。PL需要大胆的推理，行动，以及探索。",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "火之将熄（黑魂3同人模组）",
  //   "description": "罗德兰大陆是由“神明”所统治的大陆，“神明”们比普通人类更为高大，拥有名为“初火”的力量。他们凭借神力驱逐了曾经是统治者的古龙们，并建立了王国。自从这个大陆两大王国——洛斯里克和亚诺尔隆德联姻之后，迎来了繁荣昌盛的黄金时代。 pl们扮演的是生活在黄金时代的普通人（类似于低魔世界观的西方中世纪），因为某些特殊原因来到另外一个陌生（？）的地方....... ",
  //   "players": "4人秘密团",
  //   "duration": "！！",
  //   "difficulty": 2,
  //   "tags": ["黑暗之魂3"],
  //   "era": "中世纪",
  //   "requirements": "车卡，预设卡",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "日光",
  //   "skills": "战斗、交涉技能",
  //   "notes": "推荐给喜欢黑魂或者中世纪+克苏鲁世界观的人",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "猎杀之夜（血源诅咒同人模组）",
  //   "description": "本模组是以游戏《血源诅咒》（Bloodborne）的世界观和故事为基础制作的。 基本上，这是一个模仿 Bloodborne 主要流程的模组，切断与主线没有直接关系的区域和 NPC 的出现，并以此为基础重构故事，因此它与原作游戏的细节有所不同，对游戏熟悉与否皆可游玩。",
  //   "players": " 3-4人",
  //   "duration": "4-8h",
  //   "difficulty": 2,
  //   "tags": ["HO", "血源诅咒", "日模"],
  //   "era": "1890维多利亚",
  //   "requirements": "车卡",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "仮庵",
  //   "skills": "战斗技能",
  //   "notes": "推荐给喜欢《血源诅咒》和在维多利亚时代进行coc冒险的玩家",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "红舞鞋",
  //   "description": "「请不要忘记我曾送你一双红色的舞鞋\n将舞鞋的丝带交叉，鲜血爬上雪白的脚跟\n一圈又一圈，从今以后再也不会停止舞蹈\n请你穿上这双鞋为我而舞，至死方休」\n又一个春天。在千叶某区生活的玩家是○○警署的警官。这天你们与后辈的新晋警员接到了一桩奇怪的失踪案件。案件来自于芭蕾剧院的负责人，一位名叫火野东风的剧院经理的委托。『临近演出，剧院的演员却失踪了。尽管如此，我们却不知道失踪的到底是谁。在文件中无法说清，请立刻过来芭蕾剧院一趟』委托的内容十分含糊不清。如果问上级的话也只会得到不清楚的答复。",
  //   "players": "1人",
  //   "duration": "2-4h",
  //   "difficulty": 2,
  //   "tags": ["单人"],
  //   "era": "现代日本",
  //   "requirements": "车卡",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "阿梅",
  //   "skills": "御三家、手枪",
  //   "notes": "线性模组，氛围佳，通关难度小，但推理难度和达成较好结局的难度并不算很低\n职业必须为日本警察",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "42",
  //   "description": "临近午夜，在熟悉的电台演播室中醒来，断断续续无法记忆的梦还漂浮在脑海中，繁忙的工作已经刻不容缓。调整好音频与状态，与你合作多时的小导播吉姆挥手示意，从第一声“晚上好”开始，午夜电台谈心节目正式拉开帷幕——\n一切，如常",
  //   "players": "1人",
  //   "duration": "4-6h",
  //   "difficulty": 2,
  //   "tags": ["单人"],
  //   "era": "1998美国,港口,新巴博",
  //   "requirements": "车卡，预设卡",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "燕窝",
  //   "author": "Shame",
  //   "skills": "御三家、手枪",
  //   "notes": "内容十分精彩的模组，适合喜欢扮演的PL，后续可能会有的模组《怕黑》\n调查员固定职业为电台午夜节目主持人，年龄为20-30岁。",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },  
  // {
  //   "name": "燃烧的星辰",
  //   "description": "玩家将在海地的医院苏醒，并且失去了过去一周的记忆。",
  //   "players": "3-6人",
  //   "duration": "4h",
  //   "difficulty": 4,
  //   "tags": [],
  //   "era": "1930海地",
  //   "requirements": "预设卡",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "月海,小隐",
  //   "author": null,
  //   "skills": null,
  //   "notes": null,
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  // {
  //   "name": "狂气山脉",
  //   "description": "玩家将扮演攀登者，目标是征服一座最新发现的山峰。",
  //   "players": "4人",
  //   "duration": "4h+",
  //   "difficulty": 2,
  //   "tags": [],
  //   "era": "2012现代",
  //   "requirements": "车卡",
  //   "isNewbie": false,
  //   "type": "coc",
  //   "kp": "月海,小隐",
  //   "author": null,
  //   "skills": null,
  //   "notes": null,
  //   "mastery": "掌握模组",
  //   "weight": 1,
  // },

]
export const CocYanwoKey = CocYanwo.map(el => el.name)

// ======================================= 月海KP
export const CocYuehai = [
  {
    "name": "疯狂的艺术",
    "description": "1922年10月的一个星期三，一位伊丽莎白布什小姐联系到了你们，布什小姐请求你们帮助寻找他的兄弟迈克尔，他同时也为之前雇佣的私家侦探啊失踪而感到困惑。",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 2,
    "tags": [],
    "era": "1920美国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "铅毒之果",
    "description": "车的燃料表出了问题，这使得调查员被困在一条偏僻的路上，最近的镇子也要几英里远，但附近就有一栋大房子，住在房子里的人或许有汽油或者甚至有电话可以向外求助。",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 3,
    "tags": [],
    "era": "1920美国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 1,
  },
  {
    "name": "猩红文档",
    "description": "这个模组的事件由一场毫无预兆的死亡引发，死亡者是密斯卡托尼克大学的一名教师卡勒斯莱特教授，他死于一个奇怪的环境下并且有着侵吞和盗窃密大藏物的可能，而这可能给密大带来难以承受的丑闻。作为这所大学的一名管理者布莱斯法伦，将聘用调查员们对卡勒斯莱特的突然死亡进行调查，并且更为重要的是，对于失踪了的原本在莱特 看管下的某贵重文件进行寻找，最好是能在这文件的法定拥有者了解到这属于他的东西已经丢失了之前。",
    "players": "3-6人",
    "duration": "6-8h",
    "difficulty": 3,
    "tags": ["百分百撕卡率"],
    "era": "1920美国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海,小隐",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 1,
  },
  {
    "name": "诅咒之音",
    "description": "你们抱着不同的目的来到了一家灵异事件频发的宾馆。",
    "players": "3-6人",
    "duration": "4h",
    "difficulty": 2,
    "tags": ["日式"],
    "era": "现代日本",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海,小隐",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "复足",
    "description": "调查员受邀来到伊利诺伊州芝加哥市参加，为备受喜爱的怪奇作家哈里森·保罗·莱肯塔夫举办的为期三天的庆典，如往常一样庆典在临近芝加哥奥黑尔国际机场的曲径商业旅店举行，整个周末的内容包括：莱肯塔夫的作品讨论会、各种取材自莱肯塔夫作品的游戏以及作为压轴的粉丝自制短片首映式。",
    "players": "3-6人",
    "duration": "6h",
    "difficulty": 2,
    "tags": ["蜘蛛"],
    "era": "1920美国",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "无尽食欲",
    "description": "你们原本都在自己的人生轨迹上因为自己的目前而努力前进着，却因为一个共同的朋友“石泽先生”被聚集在了一起。你们并不知道发生了什么，但是都记得当时的通话内容“近来可好我的老朋友，说起来有些唐突，我知道你是一个很出色并且有能力的人，我需要你的帮助。”有些寒冷的秋风讲你们从回忆之中拉了回来，你们看着这个记忆中枯瘦的年轻人，他如今已是一副大腹便便的模样，站在饭店的门口笑盈盈的迎接着你们。究竟是什么样的事情需要这么多人才能解决，你不禁感到一阵好奇。",
    "players": "3-6人",
    "duration": "8h+",
    "difficulty": 2,
    "tags": ["日式", "重口"],
    "era": "现代日本",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "coc",
    "kp": "月海,小隐",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "掌握模组",
    "weight": 0,
  },
  // 分解器
]
export const CocYuehaiKey = CocYuehai.map(el => el.name)

// ======================================= 暂时店内的一些本(能力强的能带)
export const CocStore = [
  {
    name: "《幽暗之门》",
    originName: "Doors To Darkness",
    description: "官方守秘人手册中包含的经典模组合集，涵盖了多个入门级和进阶级冒险。",
    players: "3-6人",
    duration: "多样",
    difficulty: 1,
    tags: ["官方", "合集", "经典", "入门"],
    era: "1920美国",
    requirements: "标准车卡",
    isNewbie: true,
    type: "coc",
    kp: "",
    author: "Chaosium Inc. 官方",
    skills: "",
    notes: "",
    mastery: "",
    // cocType: "标准COC",
    isCollection: true,
    weight: 0,
    modules: [
      {
        "name": "了却幻梦",
        "originName": "None more Black",
        "description": "密斯卡托尼克大学学生死亡事件，事件背后另有邪恶交易？！",
        "players": "2-6人",
        "duration": "4-8h",
        "difficulty": 2,
        "tags": [],
        "era": "1920美国,密大",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "Brian M. Sammons",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 1,
      },
      {
        "name": "岭下暗影",
        "originName": "The Darkness Beneath the Hill",
        "description": "调查员们被他们的一位熟人，乔什·文斯考特召集在一起，后者近日在其地窖中找到了一条隧道。",
        "players": "2-6人",
        "duration": "???",
        "difficulty": 1,
        "tags": [],
        "era": "1920英国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "Christopher Smith Adair",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "哈索恩山",
        "originName": "Genius Loci",
        "description": "绝望的呼救与平静的拒绝，竟出自同一人之口。\n当挚友同时向你传递极致的恐惧与诡异的安宁，你意识到——有些真相，必须亲自揭开。",
        "players": "2-6人",
        "duration": "???",
        "difficulty": 1,
        "tags": [],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "Brian Courtemanche",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "湖之仆从",
        "originName": "Servants of the Lake",
        "description": "一位名为杰拉德·弗雷泽的银行家通过电话联系上了调查员们，委托他们帮忙寻找自己失踪的儿子詹姆斯。",
        "players": "2-4人",
        "duration": "???",
        "difficulty": 2,
        "tags": [],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "Glynn Owen Barrass",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "血浓于水",
        "originName": "Ties that Bind",
        "description": "您的到来，源于一位位高权重的女士的紧急委托。她的工地因这“发现”而彻底停滞，某种难以言喻的不安开始在场上蔓延。",
        "players": "2-6人",
        "duration": "???",
        "difficulty": 1,
        "tags": [],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "Tom Lynch",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
    ],
  },
  {
    name: "《旧日支配者们》",
    originName: "The Great Old Ones",
    description: "官方经典模组合集，涵盖了多个难度较高的冒险冒险。",
    players: "3-6人",
    duration: "多样",
    difficulty: 3,
    tags: ["官方", "克苏鲁", "经典", "标准"],
    era: "1920美国",
    requirements: "标准车卡",
    isNewbie: false,
    type: "coc",
    kp: "",
    author: "Chaosium",
    skills: "",
    notes: "",
    mastery: "",
    // cocType: "标准COC",
    isCollection: true,
    weight: 0,
    modules: [
      {
        "name": "孽生",
        "originName": "The Spawn",
        "description": "其调查员们到了蛮荒般的西部调查一宗谋杀案，观察阶级冲突，并发现比预期更多的恶意。",
        "players": "3-6人",
        "duration": "8h+",
        "difficulty": 3,
        "tags": [],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "Harry Cleaver",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "禁止之水",
        "originName": "Still Water",
        "description": "调查员们接了简单的任务往东边去了，在血粼粼的惨剧之中，发现所有藏书狂都是同类...",
        "players": "3-6人",
        "duration": "6-8h",
        "difficulty": 2,
        "tags": [],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "L.N.Isynwill, Doug Lyons",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "告诉我, 汝是否见过黄色邪印",
        "originName": "Tell Me, Have You Seen The Yellow Sign",
        "description": "我们的英雄来到新奥尔良，追寻英勇的往昔，却被卷入恐怖的当下。",
        "players": "3-6人",
        "duration": "???",
        "difficulty": 3,
        "tags": [],
        "era": "192_美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "Kevin A. Ross",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "暗中来客",
        "originName": "One In Darkness",
        "description": "一个年轻的记者需要得到帮助，虽然一般而言震撼波士顿的犯罪浪潮与他毫无关系。",
        "players": "3-6人",
        "duration": "8h+",
        "difficulty": 2,
        "tags": [],
        "era": "1920美国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "Doug Lyons with L.N.Isynwill",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "苍白的神",
        "originName": "The Pale God",
        "description": "调查员在对一所臭名昭著的农舍进行调查时，面临着一场惊心动魄的死亡。",
        "players": "3-6人",
        "duration": "???",
        "difficulty": 3,
        "tags": [],
        "era": "1920英国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "Kevin A. Ross",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "恶月当空",
        "originName": "Bad Moon Rising",
        "description": "调查员参加了一个科学会议，懂得如何尊重恐惧，通过一次奇怪的旅程通往更加奇异的终点。",
        "players": "3-6人",
        "duration": "???",
        "difficulty": 3,
        "tags": [],
        "era": "192_英国",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "coc",
        "kp": "月海,小隐",
        "author": "Marcus L. Rowland",
        "skills": "",
        "notes": "",
        "mastery": "",
        "weight": 0,
      },
    ],
  },
]
export const CocStoreKey = CocStore.map(el => el.name)

// ======================================= 小隐KP
export const CocXiaoyin = [
  {
    "name": "缅域",
    "originName": "Myanmar",
    "description": "",
    "players": "3-6人",
    "duration": "4-8h",
    "difficulty": 1,
    "tags": ["进阶"],
    "era": "近代中国",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "coc",
    "kp": "小隐",
    "author": "",
    "skills": "",
    "notes": "",
    "mastery": "",
    "weight": -1,
  },
  {
    "name": "死光",
    "originName": "Dead Light",
    "description": "1920年夏夜，你们驱车前往波士顿。暴雨骤至，车灯前隐约照出道路尽头一点昏暗的灯火。那或许是唯一的避雨处。",
    "players": "3-6人",
    "duration": "3-5h",
    "difficulty": 1,
    "tags": ["新手本"],
    "era": "1920美国",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "coc",
    "kp": "小隐",
    "author": "Alan Bligh",
    "skills": "",
    "notes": "",
    "mastery": "",
    "weight": 0,
  },
  {
    "name": "无光的灯塔",
    "originName": "The Lightless Beacon",
    "description": "航标岛灯塔的意外熄灭，令你们的航船触礁沉没。此刻，你们正乘着一叶小舟，在暴风雨中驶向那座黑暗的灯塔寻求庇护。然而，灯塔中等待你们的并非安全，而是一场深入未知恐怖的冒险。",
    "players": "3-6人",
    "duration": "3-5h",
    "difficulty": 1,
    "tags": ["新手本"],
    "era": "1920美国",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "coc",
    "kp": "小隐",
    "author": "Leigh Carr, Lynne Hardy",
    "skills": "",
    "notes": "",
    "mastery": "",
    "weight": 0,
  },
]
export const CocXiaoyinKey = CocXiaoyin.map(el => el.name)

// ======================================= 六KP
export const CocLiu = [
  {
    "name": "23号休息站",
    "originName": "无",
    "description": "你从没见过像这样的暴风雪，十月的爱达荷山脉的天气可能不太好，但现在出现在你们面前的却是一片白色的苍茫大地……",
    "players": "3-6人",
    "duration": "4-5h",
    "difficulty": 1,
    "tags": ["新手本"],
    "era": "现代美国",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "coc",
    "kp": "六",
    "author": "无",
    "skills": "无",
    "notes": "纯新人模组",
    "mastery": "掌握",
    "weight": -1,
  },
]
export const CocLiuKey = CocLiu.map(el => el.name)

// ======================================= 合并并排序的模组列表
export const CocAllModules = [...CocYanwo, ...CocYuehai, ...CocStore, ...CocXiaoyin, ...CocLiu]
  .sort((a, b) => {
    // 先排新手
    // 第一优先级：isNewbie (true 在前) 
    if (a.isNewbie !== b.isNewbie) {
      return a.isNewbie ? -1 : 1
    }
    
    // 第二优先级：权重 (有值且数值大的在前)
    if (a.weight !== b.weight) {
      // 如果都有权重，按权重降序
      if (a.weight !== null && b.weight !== null) {
        return b.weight - a.weight
      }
      // 只有一个有权重，有权重的在前
      if (a.weight !== null) return -1
      if (b.weight !== null) return 1
    }
    
    // 第三优先级：难度 (数值小的在前)
    return a.difficulty - b.difficulty
  })
// 排序的改一下 ✅
  
// 上一些双人模组 纯新手开 车卡和跑团分开收费
// 追书人

// 有合集的模组 用合集名归类 ✅