
// ======================================= 月海KP
export const DndYuehai = [
  {
    "name": "追捕克仑可",
    "originName": "Krenko's Way",
    "description": "臭名昭著的鬼怪犯罪头目克仑可趁乱从乌泽监狱逃了出来。速速将他捉拿归案！",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 1,
    "tags": ["新人模组", "战斗居多", "事件驱动", "线性"],
    "era": "",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "dnd5E",
    "kp": "月海,小天",
    "author": null,
    "skills": null,
    "notes": "长度：一次结团\n等级：一级开卡，结团升至二级",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "凡达林的失落矿坑",
    "originName": "Lost Mine Of Phandelver",
    "description": "你们也许是初出茅庐的冒险者，也许是为了名利前来的野心家，也许是一个有名的矮人商人——甘德论·巡岩者的朋友，无论如何，你们都一起走上了这场探索失落的矿洞的，惊奇的冒险之旅。",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 1,
    "tags": ["新人模组", "战斗居多", "事件驱动", "传统英雄故事", "线性"],
    "era": "",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "dnd5E",
    "kp": "月海",
    "author": null,
    "skills": null,
    "notes": "长度：约五次结团\n等级：一级开卡，结团升至五级",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "风骸岛之龙",
    "originName": "Dragons Of Stormwreck Isle",
    "description": "在剑湾北部，一座名为巨龙休息处的修道院坐落在风骸岛之上.其院长茹娜拉是远近闻名的智者，许多人来这里解决心中的疑惑或是寻求内心的宁静.出于某种目的，冒险者们乘上了前往风骸岛的船只。",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 1,
    "tags": ["新人模组"],
    "era": "费伦, 宝剑海风骇岛",
    "requirements": "车卡, 预设卡",
    "isNewbie": true,
    "type": "dnd5E",
    "kp": "月海",
    "author": null,
    "skills": null,
    "notes": "长度：约四次结团\n等级：一级开卡，结团升至三级",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "冰塔峰之龙",
    "originName": "Dragon Of Icespire Peak",
    "description": "凡达林小镇安定,居民勤奋，在严酷的旷野经营者他们的生活，但在不久之前，一条白龙降落在了小镇附近的宝剑山脉，作为众多励志屠龙的冒险者小队之一，你们来到了凡达林，准备通过平凡的任务，寻找屠龙的方法。",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 1,
    "tags": ["新人模组", "少儿友好"],
    "era": "费伦, 凡达林",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "dnd5E",
    "kp": "月海",
    "author": null,
    "skills": null,
    "notes": "长度：约五次结团\n等级：一级开卡，结团升至六级",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "十镇冬日",
    "originName": "Winter Of Ten Towns",
    "description": "不是所有的冬天都有火炉和热粥。不是所有的战斗都会流血。不是所有冒险都能用刀剑来解决问题。\n这里充满着蛮族的侵略以及讨伐地精的战火，还有危险的苔原雪猿跟极地巨虫。冰风谷是个现实的、残酷的世界，是一个无情的环境，在这里犯上任何一个小错误很可能就会要了你的命。……而我生活在这么一个如此美丽又如此现实的地方，一个你随时都得保持在最佳状态，小心谨慎的地方。我把它称作，天堂。",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 2,
    "tags": ["新人模组", "冰风谷:冰霜少女的雾凇"],
    "era": "剑湾",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "dnd5E",
    "kp": "月海",
    "author": null,
    "skills": null,
    "notes": "长度：约1次结团\n等级：二级开卡\n非常适合衔接《冰风谷:冰霜少女的雾凇》",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "深水城-龙金之劫",
    "originName": "Dragon Heist",
    "description": "欢迎来到深水城。在这被赞为北地之冠的地方，一段发生在城市的奇幻冒险即将展开。故事始于诸位冒险者齐聚于呵欠之门旅馆。瓦罗·赞普·格达姆，一位十分出名的探险者兼说书人，将赋予冒险者们一项令他们陷入两个邪恶组织的激烈冲突之中的任务。如果冒险者们完成了任务，瓦罗会慷慨地给予他们奖赏。然而，一笔更丰厚的奖赏就藏在这辉煌之城的某处，等待着重见天日。",
    "players": "3-5人",
    "duration": "4-6h",
    "difficulty": 3,
    "tags": ["城市冒险"],
    "era": "费伦, 深水城",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "dnd5E",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "长度：约五次结团\n等级：一级开卡，结团升至五级",
    "mastery": "",
    "weight": 0,
  },
  {
    "name": "深水城-疯法师的地城",
    "originName": "Dungeon Of The Mad Mage",
    "description": "是男人就下地城！！！ 23层地下城对应5到20级的冒险家，每层都可以是独立的团。",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 4,
    "tags": ["是男人就下一百层"],
    "era": "费伦, 深水城",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "dnd5E",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "长度：每层约1~2次，共23层\n等级：5~20级",
    "mastery": "",
    "weight": 0,
  },
  {
    "name": "施特拉德的诅咒",
    "originName": "Curse Of Strahd",
    "description": "因为各种各样的契机，冒险者们从匕首滩齐聚，前往传说中最古老的鸦阁魔域——巴洛维亚，并且直面传说中的吸血鬼的始祖：施特拉德·冯·扎洛维奇，在这阴暗恐怖的地域里，展开一段疯狂的，充满史诗感的冒险。",
    "players": "3-5人",
    "duration": "4-6h",
    "difficulty": 5,
    "tags": ["哥特风", "人物驱动", "沙盒模组", "诡秘恐怖", "探索&交涉居多", "公路团"],
    "era": "堕影冥界,巴洛维亚",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "dnd5E",
    "kp": "月海",
    "author": null,
    "skills": null,
    "notes": "长度：约十三到十五次结团\n等级：一级开卡，结团升至十级",
    "mastery": "",
    "weight": 0,
  },
  {
    "name": "冰风谷:冰霜少女的雾凇",
    "originName": "Icewind Dale: Rime of the Frostmaiden",
    "description": "世界之脊以北，瑞格冰川以西是一片鲜有人烟的寒冷之域。去那里探索的人都寥寥可数，更别提定在此定居了。这片被寒风席卷的冻土苔原最近陷入了一场不见天日的永久寒冬之中。大多数冰风谷的居民都认为这是冰霜少女欧吕尔——愤怒的寒冬之神一手造成的。据说，每晚在天空中织出的闪烁的极光就是她的杰作——那是一种强大的魔法，可以让太阳远离冰风谷。\n冰风谷的居民住在一个被称作“十镇”的零星定居点中。从南方来的稀疏商队在各定居点之间穿行，在这个永无止境的冬天，每个人都感到无比孤独。对于你们这样的冒险者来说，十镇是一个勇气的试炼所，继承前辈英雄们的精神，在这篇寒冷荒芜的土地上留下自己的印记。",
    "players": "3-5人",
    "duration": "4-6h",
    "difficulty": 5,
    "tags": ["人物驱动", "探索居多", "沙盒", "封闭空间", "寒冬求生"],
    "era": "费伦,冰风谷",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "dnd5E",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "长度：约二十一到二十三次结团\n等级：一级开卡，结团升至十二级",
    "mastery": "",
    "weight": 0,
  },
  {
    "name": "逃离深渊",
    "originName": "Out Of The Abyss",
    "description": "没人希望自己被一群卓尔俘虏，但件事偏偏就落在了你们身上，冰冷的镣铐紧锁着你们的喉咙和手腕，在这片幽暗、危险的地域，你们只想做一件事——逃出去。",
    "players": "3-5人",
    "duration": "4-6h",
    "difficulty": 5,
    "tags": ["人物驱动", "探索居多", "沙盒", "封闭空间", "寒冬求生"],
    "era": "费伦,幽暗地域",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "dnd5E",
    "kp": "月海",
    "author": "",
    "skills": "",
    "notes": "模组可分为上下两部\n上:约十到十二次结团, 一到八级\n下: 约十到十二次结团, 八到十五级\n总长度：约二十一到二十三次结团\n等级：一级开卡，结团升至十五级",
    "mastery": "",
    "weight": 0,
  },
  {
    name: "《哈欠门故事集》",
    originName: "The Sleepers' Heirs",
    description: "官方经典模组合集，涵盖了多个入门级和进阶级的可单次的冒险。",
    players: "3-6人",
    duration: "多样",
    difficulty: 1,
    tags: ["官方", "哈欠门", "合集", "经典", "入门"],
    era: "费伦,哈欠门",
    requirements: "标准车卡",
    isNewbie: true,
    type: "dnd5E",
    kp: "",
    author: "Chaosium",
    skills: "",
    notes: "",
    mastery: "",
    // dnd5EType: "标准DND5E",
    isCollection: true,
    weight: 0,
    modules: [
      {
        "name": "暗无天日",
        "originName": "The Sunless Citadel",
        "description": "万事万物在此覆灭：午夜的恐怖、迷失之年的战役、不扰眠的地层和光辉耀眼的丛林;而在那海岸边回荡着的声音，仍然清晰，那是探险的骑士们发出的死亡狂喜————但，为何那风又让我们再回世间！ ————阿蒂尔·兰波",
        "players": "3-6人",
        "duration": "4-6h",
        "difficulty": 1,
        "tags": ["新人模组"],
        "era": "",
        "requirements": "车卡",
        "isNewbie": true,
        "type": "dnd5E",
        "kp": "月海,燕窝",
        "author": "BruceR Cordell",
        "skills": "",
        "notes": "等级：一级开卡，结团升至三级",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "愤怒熔炉",
        "originName": "The Forge Of Fury",
        "description": "去吧，穿越北方荒野，寻找那传说中杜尔格丁打造的神兵，它仍在那古堡的深处...",
        "players": "3-6人",
        "duration": "4-6h",
        "difficulty": 2,
        "tags": [],
        "era": "",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "dnd5E",
        "kp": "月海",
        "author": "Richard Baker",
        "skills": "",
        "notes": "等级：三级级开卡，结团升至五级",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "塔莫肯秘殿",
        "originName": "The Hidden Shrine Of Tamoachan",
        "description": "你们踏上通往金字塔神殿的道路，踩过破裂的石板，绕过倒塌的石柱，拨开厚厚的藤蔓与荆棘。\n突然，大地在脚下颤抖，砖石轰鸣坍塌，你们随之坠入深渊。灰尘弥漫，阳光消失，黑暗笼罩一切。",
        "players": "3-6人",
        "duration": "4-6h",
        "difficulty": 2,
        "tags": [],
        "era": "",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "dnd5E",
        "kp": "月海",
        "author": "Harold Johnson & Jeff R Leason",
        "skills": "",
        "notes": "等级：五级开卡",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "白羽山",
        "originName": "White Plume Mountain",
        "description": "收藏家的珍贵异宝被盗，而线索指向那个怪异巫师——卡拉帕迪斯。你们受重金悬赏，踏入白羽山，穿越险境与机关，寻找失落的宝物。",
        "players": "3-6人",
        "duration": "4-6h",
        "difficulty": 3,
        "tags": ["智慧"],
        "era": "",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "dnd5E",
        "kp": "月海",
        "author": "Lawrencs Schick",
        "skills": "",
        "notes": "等级：八级开卡",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "死于塞尔",
        "originName": "Dead In Thay",
        "description": "你们面前是一个阴暗的大厅，地面上的传送法阵还在闪烁着些许微光，还没来得及思考你们的处境，一位女性红袍法师的影像就突然显现：\n“我是西岚娜“她说： ”是我把你们带到这儿来的，总之，欢迎来到赛尔！”",
        "players": "3-6人",
        "duration": "4-6h",
        "difficulty": 3,
        "tags": [],
        "era": "",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "dnd5E",
        "kp": "月海",
        "author": "Scott Fitzgerald Gray",
        "skills": "",
        "notes": "等级：九到十一级开卡",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "巨人之战",
        "originName": "Against The Giants",
        "description": "巨人氏族联合劫掠文明，死亡与毁灭随处蔓延。王国召集了最勇敢、最强大的冒险者——你们，组成一支精锐特遣小队。\n这是属于冒险者的战场，也是智慧与胆识的试炼场。",
        "players": "3-6人",
        "duration": "4-6h",
        "difficulty": 4,
        "tags": ["战略"],
        "era": "",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "dnd5E",
        "kp": "月海",
        "author": "Scott Fitzgerald Gray",
        "skills": "",
        "notes": "等级：十一级开卡",
        "mastery": "",
        "weight": 0,
      },
      {
        "name": "恐怖之墓",
        "originName": "Tomb Of Horrors",
        "description": "在遥远荒丘的地下，埋藏着一座被无数传说笼罩的墓穴。迷宫般的通道中布满残酷的陷阱与潜伏的怪物，无数冒险者在此折戟沉沙，鲜血早已染红石壁。然而，宝藏与魔力的传闻从未停息——但真正的恐惧，源自那位栖身其中的大巫妖，一个几乎无法战胜的存在。这里...是勇气与智慧的终极试炼之地",
        "players": "3-6人",
        "duration": "4-6h",
        "difficulty": 5,
        "tags": ["智慧"],
        "era": "",
        "requirements": "车卡",
        "isNewbie": false,
        "type": "dnd5E",
        "kp": "月海",
        "author": "加里·吉加克斯",
        "skills": "",
        "notes": "长度：约???次结团\n等级：???级开卡",
        "mastery": "",
        "weight": 0,
      },
    ],
  },
  // 死亡之屋 (进阶 俩厂结束 可作为cos的前置导入)
  // 巫光之外 前两个模组
]
export const DndYuehaiKey = DndYuehai.map(el => el.name)

// ======================================= 燕窝KP
export const DndYanwo = [
  {
    "name": "雪夜怪谈",
    "description": "起因：一位牧师委托你们前往雪山中的修道院看望自己的弟弟——掌门人阿鲁津。",
    "players": "4人",
    "duration": "6-7h",
    "difficulty": 1,
    "tags": [],
    "era": "",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "dnd5E",
    "kp": "燕窝",
    "author": " Mads Hvelplund",
    "skills": "",
    "notes": "dnd入门团，推荐给新手，后续可以衔接其他模组\n本模组不设补给点，但pc可以在正式开团之前用初始资金进行采购。\n短团，欢迎多多rp，欢迎合理搞事。 可能会有的后续模组：【魔现封神】。\n长度：一次结团\n等级：一级开卡",
    "mastery": "掌握模组",
    "weight": 0,
  },
  // {
  //   "name": "暗无天日",
  //   "description": "很久很久以前，一座巨大的城堡由于某种原因陷入地下。现在，残暴的怪物在厅堂中徘徊，邪恶在城堡中逐渐滋长。城堡底层枯萎的花园中，有人正在培育扭曲的树木。\n十二年前，为了证实“魔法苹果”的传言，放逐者贝利克来到这座城堡。他发现这座古老的建筑是由于某种魔法力量才陷入地下。在摆平城堡中的新居民后，贝利克在底层黄昏树丛的中心发现了自己寻找的目标，一根曾经钉在吸血鬼心脏上的古老木桩生根发芽，长成一颗被称为“甘提亚斯”的大树。夏至时，甘提亚斯树会结出一枚鲜红的苹果，为人们带来青春。冬至时，甘提亚斯树会结出一枚苍白的苹果，为人们带来死亡。贝利克在附近的区域散布两种苹果，为人们带来幸福与噩梦。但无论苹果的颜色，甘提亚斯树的种子都会成长为微似人形的活化幼树，在附近繁衍活动。",
  //   "players": "4人",
  //   "duration": "8h",
  //   "difficulty": 1,
  //   "tags": [],
  //   "era": "",
  //   "requirements": "车卡",
  //   "isNewbie": true,
  //   "type": "dnd5E",
  //   "kp": "燕窝",
  //   "author": null,
  //   "skills": "",
  //   "notes": "dnd入门团，推荐给新手，后续可以衔接其他模组\n长度：约一到二次结团\n等级：一级开卡，最终达到二级甚至三级",
  //   "mastery": "掌握模组",
  //   "weight": 0,
  // },
  {
    "name": "林中魅影",
    "description": "朽木镇旁的黑血森林常年来一直为镇民津津乐道，据说：镇长有一个善良而美丽的女儿，名叫奥莉雅。她深受大家的喜爱，但有一天，奥莉雅收留了一个外地来的旅人，却不曾想到那个旅者竟然是一个林中魅影！那晚正好是月圆之夜，残暴的林中魅影虽然被杀死，但奥莉雅却不幸被咬伤，她感觉到自己身体的异样，知道自己已经染上了诅咒，于是便在黑血森林中上吊了。从那以后，那片森林便被迷雾所笼罩，而那奥莉雅的魂灵则在迷雾中游荡......\n但这还没完，黑血森林的迷雾似乎在逐渐地向外蔓延，许多离森林近的村子都被迷雾所覆盖，变成了死镇。\n镇民们十分惊慌，镇长也发出委托，希望有人能解决黑血森林的异变，但所有进入迷雾中的人都没能再回来。",
    "players": "4人",
    "duration": "5-7h",
    "difficulty": 3,
    "tags": [],
    "era": "",
    "requirements": "车卡",
    "isNewbie": false,
    "type": "dnd5R",
    "kp": "燕窝",
    "author": null,
    "skills": "",
    "notes": "身份：你可以是朽木镇本地人，可以是正巧旅行到这里的旅者，也可以是镇长从城里找来的雇佣兵……。5级开卡，全拓展，可以有三个非普通物品（+1武器和+1防具也是非普通）+1治疗药水+3天的干粮+一些身份有关的个人物品\n等级：五级开卡，适合老手",
    "mastery": "掌握模组",
    "weight": 0,
  },
]
export const DndYanwoKey = DndYanwo.map(el => el.name)

// ======================================= 六KP
export const DndLiu = [
  {
    "name": "苍白女王的勇士",
    "originName": "无",
    "description": "在野外的旅途，面前的道路被商队的马车堵死了，看起来还有人群聚集，发生了什么？",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 1,
    "tags": ["新手适宜", "社交", "战斗", "等级可变动"],
    "era": "",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "dnd5E",
    "kp": "6",
    "author": null,
    "skills": null,
    "notes": "长度：单次团，1/3/5级开卡",
    "mastery": "掌握模组",
    "weight": 0,
  },
  {
    "name": "枯木哀歌",
    "originName": "无",
    "description": "尊敬的冒险者大人，求求你们，我的父亲在和我们一起伐木的时候被妖物掳走了，就在迷雾森林附近，求求你们救救他！",
    "players": "3-6人",
    "duration": "4-6h",
    "difficulty": 1,
    "tags": ["新手适宜", "社交", "战斗", "冒险中升级"],
    "era": "",
    "requirements": "车卡",
    "isNewbie": true,
    "type": "dnd5E",
    "kp": "6",
    "author": null,
    "skills": null,
    "notes": "长度：单次团，1/3/5级开卡",
    "mastery": "掌握模组",
    "weight": 0,
  },
]
export const DndLiuKey = DndLiu.map(el => el.name)

// ======================================= 合并并排序的模组列表
export const DndAllModules = [...DndYuehai, ...DndYanwo, ...DndLiu]
  .sort((a, b) => {
    // 首先按 isNewbie 排序，true 的排在前面
    if (a.isNewbie !== b.isNewbie) {
      return a.isNewbie ? -1 : 1
    }
    // 然后按 difficulty 从小到大排序
    return a.difficulty - b.difficulty
  })